#!/bin/zsh

BUILDDIR=${1-cmd/sitepod-cm/}

LASTPID=
FIRSTRUN=true

while (true) {
  if [ -z "$FIRSTRUN" ]; then
    echo "Waiting"
    inotifywait -e close_write **/*.go
  fi
  FIRSTRUN=
  if [ -n "$LASTPID" ]; then
    echo "Killing $LASTPID"
    kill $LASTPID
  fi
  sleep 0.2
  echo "Files changed"
  echo "Using bild $BUILDDIR"
  hack/build $BUILDDIR
  if [ $? -eq 0 ]; then
    echo "Runnign fresh"
    hack/run &
    LASTPID=$!
    echo "LASTPID is $LASTPID"
  else
    echo "Bad build"
    LASTPID=
  fi
}
